trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
    - task: Bash@3
      displayName: 'Run a single JavaScript file'
      inputs:
        targetType: inline
        script: |
          echo "Run the JavaScript file: execute.js"
          node execute.js